version: '2'
services:

  vault:
    container_name: vault.server
    command: server
    image: vault:latest
    volumes:
      - ./test/util/vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    depends_on:
      - consul

  consul:
    container_name: consul.server
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
    image: consul:latest
    volumes:
      - ./test/util/consul/config:/consul/config
    ports:
      - "9300:9300"
      - "9500:9500"
      - "9600:9600/udp"